library(usethis)
library(devtools)
library(roxygen2)
library(BiocCheck)
load_all();document();roxygenize()
library(scQTLtools)
check()
check(vignettes = FALSE)
devtools::build()
BiocCheck::BiocCheck('scQTLtools' = TRUE)
 BiocCheck::BiocCheckGitClone(package = '.')
readCitationFile("inst/CITATION")
